# MPI-based makefile using mpic++ and mpicc.

CC =		mpicc 
CPP =		mpic++ 
CCFLAGS =	-g -O -I../src -m64
LINK =		mpic++
LINKFLAGS =	-g -O -m64
#USRLIB =	../src/libmrmpi.a 
USRLIB =	-L../src -lmrmpi
SYSLIB =

LIB =		../src/libmrmpi.a

include Makefile.common
